### PR TITLE
Support single valued and empty arrays for all supported types

### LINKED ISSUE #21: DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS not respected
the following JSON
```
{"zdt":["2017-03-22T14:50:08.121+01:00"]}
```
Cannot be deserialized into the following class:
```
public static class TestJava8TimeBean{
		private ZonedDateTime zdt=ZonedDateTime.now();
		
		public TestJava8TimeBean(){
			
			
		}
		
		public ZonedDateTime getZdt() {
			return zdt;
		}
		
		public void setZdt(ZonedDateTime zdt) {
			this.zdt = zdt;
		}
``` 
But the mapper I use defines:
```
mapper.configure(DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS, true);
```
So using an array with one value should work. It does with strings. Also probably if DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT is enabled, an empty array should result in a null value.

### PR DESCRIPTION
**Pull request by JPMoresmau**
Should fix #21 , added tests for all types to verify behavior for non empty and empty arrays.

### CODE REVIEW

**Comment by JPMoresmau** [comment]
On my machine I had to change the parent pom.xml to use the latest version of databind with https://github.com/FasterXML/jackson-databind/commit/60ae6000d361f910ab0d7d269a5bac1fc66f4cd9

**Comment by cowtowncoder** [comment]
Excellent. Yes, method for convenient handling of arrays was just added, so requires post 2.9.0.pr2 `jackson-databind`.

I'll be happy to merge this. Just one formality (unless I've already this asked for this): Contributor License Agreement, from: 

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

usually easiest to print, fill & sign, scan, email to `info` at fasterxml dot com.
Only needs to be done once, good for all contributions for Jackson projects.
If we could get that I'll merge this ASAP.

Thank you in advance!

**Comment by JPMoresmau** [comment]
OK, sent you a CLA via email.

**Comment by cowtowncoder** [comment]
Excellent, merging!

**Pull request merged**
