### PR TITLE
add handling of JsonFormat.Feature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS

### LINKED ISSUE #272: JsonFormat.Feature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS not respected when deserialising Instants
I have a class as follows:

```java
public class InstantWrapper {
    @JsonFormat(without = Feature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS)
    private Instant myInstant;

    public Instant getMyInstant() { return myInstant; }
    public void setMyInstant(Instant myInstant) { this.myInstant = myInstant; }
}
```

When serialising, the result uses milliseconds since the epoch; however, when deserialising, it is interpreted as nanoseconds.

I understand that the JavaDoc says "Override for `SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS`" (saying nothing about `DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS`), however in my view it's undesirable that a round-trip modifies the data when this option is used.

Is there a way (other than writing my own deserialiser) to override the ObjectMapper's settings so that timestamps are interpreted using milliseconds?

### PR DESCRIPTION
**Pull request by raman-babich**
Fixes #272

### CODE REVIEW

**Comment by raman-babich** [comment]
To fix #272

**Comment by cowtowncoder** [comment]
Thank you for submitting this, @raman-babich ! I hope to review that in near future, but I do have some backlog. Maybe others can give feedback in the meantime.

Also; unless we have CLA from you, before merging the first PR, we'd need it from here:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

(usual way being to print it, fill & sign, scan/photo, email to `info` at fasterxml dot com)

and once we have it (only needed once so if you have sent one before, just let us know) merging is possible.

Thank you once again & looking forward to getting this merged!

**Comment by raman-babich** [comment]
What should I specify as a project name, jackson or jackson-module-java8?

**Comment by cowtowncoder** [comment]
@raman-babich Sorry I missed this: feel free to just use "Jackson" (both work fwtw but generic is better)

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Thank you @raman-babich !

**Pull request merged**
